### account creation request

POST http://localhost:4001/auth/create-user
Content-Type: application/json

{
    "email": "BigLenns@gmail.com",
    "password": "password"
}

### login user
POST http://localhost:4001/auth/login
Content-Type: application/json

{
    "email": "BigLensss@gmail.com",
    "password": "password"
}